name: Deploy to Hugging Face Space
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: infinity-agent
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade huggingface_hub==0.23.0
      - name: Deploy via huggingface_hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi(token=os.environ['HF_TOKEN'])
          sid = os.environ['HF_SPACE_ID']
          api.create_repo(repo_id=sid, repo_type='space', space_sdk='nodejs', private=False, exist_ok=True)
          api.upload_folder(repo_id=sid, repo_type='space', folder_path='.', path_in_repo='.', commit_message='CI: deploy latest', ignore_patterns=['.git*','.github/*','node_modules/*'])
          print('Deploy done ✅')
          PY
